# Utilizando módulo Olho Vivo API

Módulos necessários até o momento:
- python-dotenv
- requests
- pandas

Para instalar no ambiente:
```
pip install python-dotenv requests pandas
```

---

In [1]:
# Importa dependências

import os
from dotenv import load_dotenv

# Importa o módulo api_olhovivo e autentica no Olho Vivo API
import sys
sys.path.insert(0, '../modules')
import api_olhovivo

Aqui é importante que seja copiado manualmente o arquivo .env com o TOKEN de acesso para a API do Olho Vivo.

Ref: https://www.sptrans.com.br/desenvolvedores/api-do-olho-vivo-guia-de-referencia/

In [2]:
load_dotenv()  # Carrega as variáveis de ambiente do arquivo .env
# Acesse o token de API do arquivo .env
api_token = os.getenv("API_TOKEN")
# print(api_token)
api = api_olhovivo.OlhoVivoAPI(api_token)

Autenticação bem-sucedida!

---

### Buscar informação de Linha de Ônibus
#### Argumento
- **termosBusca** (str): Aceita denominação ou número da linha (total ou parcial).
Exemplo: 8000, Lapa ou Ramos

#### Retorno
A resposta da API convertida em um dicionário Python, ou None se a requisição falhar.
- **cl** (int): Código identificador da linha. Este é um código identificador único de cada linha do sistema (por sentido de operação)
- **lc** (bool): Indica se uma linha opera no modo circular (sem um terminal secundário)
- **lt** (string): Informa a primeira parte do letreiro numérico da linha
- **tl** (int): Informa a segunda parte do letreiro numérico da linha, que indica se a linha opera nos modos: BASE (10), ATENDIMENTO (21, 23, 32, 41)
- **sl** (int): Informa o sentido ao qual a linha atende, onde 1 significa Terminal Principal para Terminal Secundário e 2 para Terminal Secundário para Terminal Principal
- **tp** (string): Informa o letreiro descritivo da linha no sentido Terminal Principal para Terminal Secundário
- **ts** (string): Informa o letreiro descritivo da linha no sentido Terminal Secundário para Terminal Principal

In [3]:
# Faz uma chamada para obter informações sobre a linha 8040
# info_linha = api.buscar_linha('8040')
info_linha = api.buscar_linha('Universitária')
print(info_linha)
if info_linha==[]:
    print('Veio vazio')

# Imprime  informações sobre a linha 8040
import pandas as pd
df_info_linhas = pd.DataFrame(info_linha)
df_info_linhas

[{'cl': 630, 'lc': False, 'lt': '177H', 'sl': 1, 'tl': 10, 'tp': 'CID. UNIVERSITÁRIA', 'ts': 'METRÔ SANTANA'}, {'cl': 33398, 'lc': False, 'lt': '177H', 'sl': 2, 'tl': 10, 'tp': 'CID. UNIVERSITÁRIA', 'ts': 'METRÔ SANTANA'}, {'cl': 657, 'lc': False, 'lt': '701U', 'sl': 1, 'tl': 10, 'tp': 'CID. UNIVERSITÁRIA', 'ts': 'METRÔ SANTANA'}, {'cl': 33425, 'lc': False, 'lt': '701U', 'sl': 2, 'tl': 10, 'tp': 'CID. UNIVERSITÁRIA', 'ts': 'METRÔ SANTANA'}, {'cl': 2023, 'lc': False, 'lt': '8012', 'sl': 1, 'tl': 10, 'tp': 'CID. UNIVERSITÁRIA', 'ts': 'METRÔ BUTANTÃ'}, {'cl': 34791, 'lc': False, 'lt': '8012', 'sl': 2, 'tl': 10, 'tp': 'CID. UNIVERSITÁRIA', 'ts': 'METRÔ BUTANTÃ'}, {'cl': 2085, 'lc': False, 'lt': '8022', 'sl': 1, 'tl': 10, 'tp': 'CID. UNIVERSITÁRIA', 'ts': 'METRÔ BUTANTÃ'}, {'cl': 34853, 'lc': False, 'lt': '8022', 'sl': 2, 'tl': 10, 'tp': 'CID. UNIVERSITÁRIA', 'ts': 'METRÔ BUTANTÃ'}, {'cl': 2545, 'lc': True, 'lt': '8032', 'sl': 1, 'tl': 10, 'tp': 'CID. UNIVERSITÁRIA', 'ts': 'METRÔ BUTANTÃ'}, {'cl': 35313, 'lc': True, 'lt': '8032', 'sl': 2, 'tl': 10, 'tp': 'CID. UNIVERSITÁRIA', 'ts': 'METRÔ BUTANTÃ'}, {'cl': 1330, 'lc': False, 'lt': '702U', 'sl': 1, 'tl': 10, 'tp': 'TERM. PQ. D. PEDRO II', 'ts': 'CID. UNIVERSITÁRIA'}, {'cl': 34098, 'lc': False, 'lt': '702U', 'sl': 2, 'tl': 10, 'tp': 'TERM. PQ. D. PEDRO II', 'ts': 'CID. UNIVERSITÁRIA'}, {'cl': 1332, 'lc': False, 'lt': '7181', 'sl': 1, 'tl': 10, 'tp': 'TERM. PRINC. ISABEL', 'ts': 'CID. UNIVERSITÁRIA'}, {'cl': 34100, 'lc': False, 'lt': '7181', 'sl': 2, 'tl': 10, 'tp': 'TERM. PRINC. ISABEL', 'ts': 'CID. UNIVERSITÁRIA'}, {'cl': 1376, 'lc': True, 'lt': '7411', 'sl': 1, 'tl': 10, 'tp': 'PÇA. DA SÉ', 'ts': 'CID. UNIVERSITÁRIA'}, {'cl': 34144, 'lc': True, 'lt': '7411', 'sl': 2, 'tl': 10, 'tp': 'PÇA. DA SÉ', 'ts': 'CID. UNIVERSITÁRIA'}, {'cl': 2254, 'lc': False, 'lt': '809U', 'sl': 1, 'tl': 10, 'tp': 'METRÔ BARRA FUNDA', 'ts': 'CID. UNIVERSITÁRIA'}, {'cl': 35022, 'lc': False, 'lt': '809U', 'sl': 2, 'tl': 10, 'tp': 'METRÔ BARRA FUNDA', 'ts': 'CID. UNIVERSITÁRIA'}]

       cl     lc    lt  sl  tl                     tp                  ts
0     630  False  177H   1  10     CID. UNIVERSITÁRIA       METRÔ SANTANA
1   33398  False  177H   2  10     CID. UNIVERSITÁRIA       METRÔ SANTANA
2     657  False  701U   1  10     CID. UNIVERSITÁRIA       METRÔ SANTANA
3   33425  False  701U   2  10     CID. UNIVERSITÁRIA       METRÔ SANTANA
4    2023  False  8012   1  10     CID. UNIVERSITÁRIA       METRÔ BUTANTÃ
5   34791  False  8012   2  10     CID. UNIVERSITÁRIA       METRÔ BUTANTÃ
6    2085  False  8022   1  10     CID. UNIVERSITÁRIA       METRÔ BUTANTÃ
7   34853  False  8022   2  10     CID. UNIVERSITÁRIA       METRÔ BUTANTÃ
8    2545   True  8032   1  10     CID. UNIVERSITÁRIA       METRÔ BUTANTÃ
9   35313   True  8032   2  10     CID. UNIVERSITÁRIA       METRÔ BUTANTÃ
10   1330  False  702U   1  10  TERM. PQ. D. PEDRO II  CID. UNIVERSITÁRIA
11  34098  False  702U   2  10  TERM. PQ. D. PEDRO II  CID. UNIVERSITÁRIA
12   1332  False  7181   1  10    TERM. PRINC. ISABEL  CID. UNIVERSITÁRIA
13  34100  False  7181   2  10    TERM. PRINC. ISABEL  CID. UNIVERSITÁRIA
14   1376   True  7411   1  10             PÇA. DA SÉ  CID. UNIVERSITÁRIA
15  34144   True  7411   2  10             PÇA. DA SÉ  CID. UNIVERSITÁRIA
16   2254  False  809U   1  10      METRÔ BARRA FUNDA  CID. UNIVERSITÁRIA
17  35022  False  809U   2  10      METRÔ BARRA FUNDA  CID. UNIVERSITÁRIA

---

### Buscar informação de Linha de Ônibus em sentido específico
Realiza uma busca das linhas do sistema com base no sentido da linha. Se a linha não é encontrada então é realizada uma busca fonetizada na denominação das linhas.

#### Argumento
- **codigoLinha** (str): O código da linha.
- **sentido** (str): O sentido da linha (1- ida ou 2-volta).

#### Retorno
A resposta da API convertida em um dicionário Python, ou None se a requisição falhar.
- **cl** (int): Código identificador da linha. Este é um código identificador único de cada linha do sistema (por sentido de operação)
- **lc** (bool): Indica se uma linha opera no modo circular (sem um terminal secundário)
- **lt** (string): Informa a primeira parte do letreiro numérico da linha
- **tl** (int): Informa a segunda parte do letreiro numérico da linha, que indica se a linha opera nos modos: BASE (10), ATENDIMENTO (21, 23, 32, 41)
- **sl** (int): Informa o sentido ao qual a linha atende, onde 1 significa Terminal Principal para Terminal Secundário e 2 para Terminal Secundário para Terminal Principal
- **tp** (string): Informa o letreiro descritivo da linha no sentido Terminal Principal para Terminal Secundário
- **ts** (string): Informa o letreiro descritivo da linha no sentido Terminal Secundário para Terminal Principal

In [4]:
# Faz uma chamada para buscar informações sobre o sentido da linha 8040
info_linha_sentido = api.buscar_linha_sentido('8040','1')


# Imprime  informações sobre a linha 8040
import pandas as pd
df_info_linha_sentido = pd.DataFrame(info_linha_sentido)
df_info_linha_sentido

    cl     lc    lt  sl  tl          tp            ts
0  406  False  8040   1  10  TERM. LAPA  SOL NASCENTE

---

### Buscar paradas
Realiza uma busca fonética das paradas de ônibus do sistema com base no parâmetro informado. A consulta é realizada no nome da parada e também no seu endereço de localização.
        
#### Argumentos:
- **termosBusca** (str): Aceita nome da parada ou endereço de localização (total ou parcial).
Exemplo: Afonso, ou Balthazar da Veiga

#### Retorno:
A resposta da API convertida em um dicionário Python, ou None se a requisição falhar.
- **cp** (int): Código identificador da parada
- **np** (string): Nome da parada
- **ed** (string): Endereço de localização da parada
- **py** (double): Latitude da parada
- **px** (double): Longitude da parada

In [5]:
# Faz uma chamada para buscar informações sobre todas as paradas
info_paradas = api.buscar_parada('Ciencia')


# Imprime  informações sobre a linha 8040
import pandas as pd
df_info_paradas = pd.DataFrame(info_paradas)
df_info_paradas

          cp           np                    ed         py         px
0  480014611  CIENCIA C/B  R SCIPIAO/ R AURELIA -23.521284 -46.698763

---

### Busca parada por Linha (Não está funcionando)
Realiza uma busca por todos os pontos de parada atendidos por uma determinada linha.

#### Argumento
- **codigoLinha** (str): Código identificador da linha. Este é um código identificador único de cada linha do sistema (por sentido) e pode ser obtido através do método buscar_linha da categoria Linhas

#### Retorno
A resposta da API convertida em um dicionário Python, ou None se a requisição falhar.
- **cp** (int): Código identificador da parada
- **np** (string): Nome da parada
- **ed** (string): Endereço de localização da parada
- **py** (double): Latitude da parada
- **px** (double): Longitude da parada

In [6]:
# Faz uma chamada para buscar informações sobre as paradas da linha 8022
info_linha = api.buscar_linha('8022')
codigo_linha = info_linha[0]['cl']

info_paradas_linha = api.buscar_paradas_por_linha('406')


print(codigo_linha)
print(info_paradas_linha)

2085
[]

---

### Buscar Corredores Inteligentes
Retorna uma lista com todos os corredores inteligentes.

#### Retorno:
A resposta da API convertida em um dicionário Python, ou None se a requisição falhar.
- **cc** (int): Código identificador da corredor. Este é um código identificador único de cada corredor inteligente do sistema
- **nc** (string): Nome do corredor

In [7]:
# Faz uma chamada para buscar informações sobre as paradas do corredor
corredores = api.buscar_corredores_inteligentes()


# Imprime  informações de corredores
import pandas as pd
df_corredores = pd.DataFrame(corredores)
df_corredores

   cc                   nc
0   8          Campo Limpo
1   9  Expresso Tiradentes
2   3      Inajar de Souza
3   7          Parelheiros
4   1             Pirituba
5   2          Santo Amaro
6  10       Paes de Barros

---

### Buscar Paradas em Corredor
Retorna a lista detalhada de todas as paradas que compõem um determinado corredor.

#### Argumento
- **codigoCorredor** (str): Código identificador do corredor. Este é um código identificador único de cada corredor do sistema e pode ser obtido através do método buscar_corredores.

#### Retorno
A resposta da API convertida em um dicionário Python, ou None se a requisição falhar.
- **cp** (int): Código indentificador da parada
- **np** (string): Nome da Parada
- **ed** (string): Endereço de localização da parada
- **py** (double): Informação de latitude da localização da parada
- **px** (double): Informação de longitude da localização da parada

In [8]:
# Faz uma chamada para buscar informações sobre as paradas do corredor 9
corredor = api.buscar_paradas_por_corredor('9')


# Imprime  informações de corredores
import pandas as pd
df_corredor = pd.DataFrame(corredor)
df_corredor

,cp,np,ed,py,px
0,3305795,CAY B/C,8000 - ESTACAO CAY BC,-23.574436,-46.603153
1,3305799,CAY C/B,8000 - ESTACAO CAY CB,-23.574453,-46.603180
2,1410076,ESTACAO ALBERTO LION B/C,6000 - ESTACAO ALBERTO LION BC,-23.564183,-46.611236
3,1410079,ESTACAO ALBERTO LION C/B,6000 - ESTACAO ALBERTO LION CB,-23.564195,-46.611271
4,1410078,ESTACAO ANA NERI C/B,5800 - ESTACAO ANA NERI CB,-23.559044,-46.614686
5,1410074,ESTAÇÃO METRÔ D. PEDRO B/C,5000 - ESTACAO METRO D. PEDRO BC,-23.550720,-46.626853
6,1410080,ESTAÇÃO METRÔ D. PEDRO C/B,5000 - ESTACAO METRO D. PEDRO CB,-23.550730,-46.626911
7,3305797,GRITO B/C,10000 - ESTACAO GRITO BC,-23.598138,-46.597172
8,3305801,GRITO C/B,10000 - ESTACAO GRITO CB,-23.598148,-46.597237
9,3305796,N.SRA APARECIDA B/C,9000 - ESTACAO NOSSA SENHORA DA APARECIDA (LEC...,-23.591353,-46.597779
10,3305800,N.SRA APARECIDA C/B,9000 - ESTACAO NOSSA SENHORA DA APARECIDA (LEC...,-23.591347,-46.597851

---

### Buscar Empresas
Retorna a lista de empresas operadoras de transporte disponíveis no sistema.

#### Retorno
A resposta da API convertida em um dicionário Python, ou None se a requisição falhar.
- **hr** (string): Horário de referência da geração das informações
- **e** (dict): Dicionário com informações da Relação de empresas por área de operação, onde:
    - **a** (int): Código da área de operação
    - **e** (dict): Relação de empresa onde:
        - **a** (int): Código da área de operação
        - **c** (int): Código de referência da empresa
        - **n** (string): Nome da empresa

In [9]:
# Faz uma chamada para buscar informações sobre as empresas operadoras de transporte
empresas = api.buscar_empresas()
# print(empresas)

# Imprime  informações de empresas
import pandas as pd

def criar_dataframe_empresas(dados_api):
  """
  Cria um DataFrame com informações de empresas e área de atuação a partir de um dicionário da API Olho Vivo.

  Args:
    dados_api: Dicionário contendo informações de empresas e área de atuação.

  Returns:
    DataFrame com colunas 'hr', 'a', 'c' e 'n'.
  """

  # Extrair hora da consulta
  hora_consulta = dados_api['hr']

  # Lista para armazenar informações das empresas
  lista_empresas = []

  # Iterar sobre as áreas de operação e empresas
  for area_operacao in dados_api['e']:
    codigo_area = area_operacao['a']
    for empresa in area_operacao['e']:
      codigo_empresa = empresa['c']
      nome_empresa = empresa['n']

      # Adicionar informações à lista
      lista_empresas.append({'hr': hora_consulta, 'a': codigo_area, 'c': codigo_empresa, 'n': nome_empresa})

  # Criar DataFrame a partir da lista
  df_empresas = pd.DataFrame(lista_empresas, columns=['hr', 'a', 'c', 'n'])

  return df_empresas

df_empresas = criar_dataframe_empresas(empresas)
df_empresas

       hr  a    c                 n
0   08:56  1   37        GATO PRETO
1   08:56  1   38     SANTA BRIGIDA
2   08:56  1  232           Spencer
3   08:56  1  235   Norte Buss S.A.
4   08:56  2   92          SAMBAIBA
5   08:56  2  232           Spencer
6   08:56  2  235   Norte Buss S.A.
7   08:56  3   50  VIAÇÃO METRÓPOLE
8   08:56  3  218        TRANSUNIÃO
9   08:56  3  237        UPBUS S.A.
10  08:56  4   80    AMBIENTAL S.A.
11  08:56  4   82           EXPRESS
12  08:56  4  224           Pêssego
13  08:56  4  233           Allibus
14  08:56  5   51       VIA SUDESTE
15  08:56  5  218        TRANSUNIÃO
16  08:56  5  236          MOVEBUSS
17  08:56  6   53     VIAÇÃO GRAJAÚ
18  08:56  6   81        MOBIBRASIL
19  08:56  6  228        Transwolff
20  08:56  6  229    A2 Transportes
21  08:56  7   27        CAMPO BELO
22  08:56  7   50  VIAÇÃO METRÓPOLE
23  08:56  7   55              KBPX
24  08:56  7   95            GATUSA
25  08:56  7  228        Transwolff
26  08:56  8   37        GATO PRETO
27  08:56  8   89        TRANSPPASS
28  08:56  8  222      ALFA RODOBUS
29  08:56  8  230          Transcap

---

### Posição dos Veículos
Retorna uma lista completa com a última localização de todos os veículos mapeados com suas devidas posições lat / long

#### Retorno
Um dicionário Python contendo a resposta da API, ou None se a requisição falhar.
- **hr** (string): Horário de referência da geração das informações
- **l** (dict): Dicionário Python contendo a Relação de linhas localizadas onde:
    - **c** (string): Letreiro completo
    - **cl** (int): Código identificador da linha
    - **sl** (int): Sentido de operação onde 1 significa de Terminal Principal para Terminal Alternativo e 2 significa de Terminal Alternativo para Terminal Principal
    - **lt0** (string): Letreiro de destino da linha
    - **lt1** (string): Letreiro de origem da linha
    - **qv** (int): Quantidade de veículos localizados
    - **vs** (dict): Dicionário Python contendo a Relação de veículos localizados, onde:
        - p (int): Prefixo do veículo
        - **a** (bool): Indica se o veículo é (true) ou não (false) acessível para pessoas com deficiência
        - **ta** (string): Indica o horário universal (UTC) em que a localização foi capturada. Essa informação está no padrão ISO 8601
        - **py** (double): Informação de latitude da localização do veículo
        - **px** (double): Informação de longitude da localização do veículo

### ToDo
- Verificar a necessidade de otimização na recuperação dos dados

In [10]:
# Retorna a Posição do Veículos
posicao_veiculos = api.posicao_veiculos()
# print(posicao_veiculos)

# Imprime informações sobre os Veículos
import pandas as pd

def criar_dataframe_veiculos(dados_api):
  """
  Cria um DataFrame com informações de veículos a partir de um dicionário da API Olho Vivo.

  Args:
    dados_api: Dicionário contendo informações de veículos.

  Returns:
    DataFrame com colunas 'hr', 'c', 'cl', 'sl', 'lt0', 'lt1', 'qv', 'p', 'a', 'ta', 'py', 'px'.
  """

  # Extrair hora da consulta
  hora_consulta = dados_api['hr']

  # Lista para armazenar informações dos veículos
  lista_veiculos = []

  # Iterar sobre as linhas e veículos
  for linha in dados_api['l']:
    codigo_linha = linha['c']
    codigo_linha_circular = linha['cl']
    sentido_linha = linha['sl']
    letreiro_0 = linha['lt0']
    letreiro_1 = linha['lt1']
    quantidade_veiculos = linha['qv']

    for veiculo in linha['vs']:
      prefixo = veiculo['p']
      acessivel = veiculo['a']
      data_hora = veiculo['ta']
      latitude = veiculo['py']
      longitude = veiculo['px']

      # Adicionar informações à lista
      lista_veiculos.append({
          'hr': hora_consulta, 
          'c': codigo_linha, 
          'cl': codigo_linha_circular,
          'sl': sentido_linha,
          'lt0': letreiro_0,
          'lt1': letreiro_1,
          'qv': quantidade_veiculos,
          'p': prefixo,
          'a': acessivel,
          'ta': data_hora,
          'py': latitude,
          'px': longitude
      })

  # Criar DataFrame a partir da lista
  df_veiculos = pd.DataFrame(lista_veiculos, columns=['hr', 'c', 'cl', 'sl', 'lt0', 'lt1', 'qv', 'p', 'a', 'ta', 'py', 'px'])

  return df_veiculos

df_veiculos = criar_dataframe_veiculos(posicao_veiculos)
df_veiculos

,hr,c,cl,sl,lt0,lt1,qv,p,a,ta,py,px
0,08:56,128Y-10,33611,2,LAPA,JD. PERY ALTO,4,26370,True,2024-05-19T11:55:43Z,-23.457446,-46.673119
1,08:56,128Y-10,33611,2,LAPA,JD. PERY ALTO,4,26131,True,2024-05-19T11:56:06Z,-23.474617,-46.666264
2,08:56,128Y-10,33611,2,LAPA,JD. PERY ALTO,4,26058,True,2024-05-19T11:56:09Z,-23.457446,-46.673119
3,08:56,128Y-10,33611,2,LAPA,JD. PERY ALTO,4,26348,True,2024-05-19T11:55:56Z,-23.519894,-46.700980
4,08:56,2723-10,33705,2,METRÔ ITAQUERA,UNIÃO DE VL. NOVA,4,45273,True,2024-05-19T11:56:16Z,-23.491492,-46.453365
...,...,...,...,...,...,...,...,...,...,...,...,...
5270,08:56,3051-10,35214,2,TERM. A. E. CARVALHO,ERMELINO MATARAZZO,1,35730,True,2024-05-19T11:55:58Z,-23.486603,-46.482687
5271,08:56,5141-10,1625,1,PÇA. DO CORREIO,TERM. SAPOPEMBA,1,52158,True,2024-05-19T11:55:50Z,-23.572844,-46.568669
5272,08:56,7267-10,1427,1,PÇA. RAMOS DE AZEVEDO,APIACÁS,1,82710,True,2024-05-19T11:56:21Z,-23.540571,-46.682409
5273,08:56,118Y-10,841,1,LAPA,LAUZANE PAULISTA,1,26346,True,2024-05-19T11:56:12Z,-23.482470,-46.657099
5274,08:56,626A-10,2596,1,MAR PAULISTA,CANTINHO DO CÉU,1,66649,False,2024-05-19T11:56:27Z,-23.697475,-46.667635

---

### Posição da Linha
Retorna uma lista com todos os veículos de uma determinada linha com suas devidas posições lat / long

#### Argumento
- **codigoLinha** (int): Código identificador da linha. Este é um código identificador único de cada linha do sistema (por sentido de operação) e pode ser obtido através do método buscar_linha.

#### Retorno:
A resposta da API convertida em um dicionário Python, ou None se a requisição falhar.
- **hr** (string): Horário de referência da geração das informações
- **vs** (dict): Relação de veículos localizados, onde:
    - **p** (int): Prefixo do veículo
    - **a** (bool):  Indica se o veículo é (true) ou não (false) acessível para pessoas com deficiência
    - **c** (int):  Código de referência da empresa
    - **ta** (string): Indica o horário universal (UTC) em que a localização foi capturada. Essa informação está no padrão ISO 8601
    - **py** (double): Informação de latitude da localização da parada
    - **px** (double): Informação de longitude da localização da parada

In [11]:
# Faz chamada para buscar informações sobre as paradas da linha 8040
codigo_linha = api.buscar_linha('8040')[0]['cl']    # 0 significa que é a linha de ida e 1 a linha de volta
print(f"Código da Linha: {codigo_linha}")
posicao = api.posicao_linha(codigo_linha)
print(posicao)

# Imprime  informações sobre a linha 8040
import pandas as pd

def criar_dataframe_veiculos_simples(dados_api):
  """
  Cria um DataFrame com informações de veículos a partir de um dicionário da API Olho Vivo (versão simplificada).

  Args:
    dados_api: Dicionário contendo informações de veículos (formato simplificado).

  Returns:
    DataFrame com colunas 'hr', 'p', 'a', 'ta', 'py', 'px'.
  """

  # Extrair hora da consulta
  hora_consulta = dados_api['hr']

  # Lista para armazenar informações dos veículos
  lista_veiculos = []

  # Iterar sobre os veículos
  for veiculo in dados_api['vs']:
    prefixo = veiculo['p']
    acessivel = veiculo['a']
    data_hora = veiculo['ta']
    latitude = veiculo['py']
    longitude = veiculo['px']

    # Adicionar informações à lista
    lista_veiculos.append({'hr': hora_consulta, 'p': prefixo, 'a': acessivel, 'ta': data_hora, 'py': latitude, 'px': longitude})

  # Criar DataFrame a partir da lista
  df_veiculos = pd.DataFrame(lista_veiculos, columns=['hr', 'p', 'a', 'ta', 'py', 'px'])

  return df_veiculos


df_posicaoLinha = criar_dataframe_veiculos_simples(posicao)
df_posicaoLinha

Código da Linha: 406
{'hr': '08:56', 'vs': [{'p': '10541', 'a': True, 'ta': '2024-05-19T11:55:50Z', 'py': -23.4395595, 'px': -46.7681375, 'sv': None, 'is': None}, {'p': '10545', 'a': True, 'ta': '2024-05-19T11:56:11Z', 'py': -23.508705749999997, 'px': -46.736869, 'sv': None, 'is': None}]}

      hr      p     a                    ta         py         px
0  08:56  10541  True  2024-05-19T11:55:50Z -23.439560 -46.768138
1  08:56  10545  True  2024-05-19T11:56:11Z -23.508706 -46.736869

---

### Posição dos veículos da Empresa na Garagem
Retorna uma lista com todos os veículos de uma determinada empresa em suas respectivas garagens

#### Argumento
- **codigoEmpresa** (int): Código identificador da empresa. Este é um código identificador único que
                    -pode ser obtido através do método buscar_empresas.
- **codigoLinha** (int, opcional): Código identificador da linha. Este é um código identificador único de cada linha do sistema (por sentido de operação) e pode ser obtido através do método buscar_linha. Se não for informado, a API retornará todos os veículos da empresa.

#### Retorno
A resposta da API convertida em um dicionário Python, ou None se a requisição falhar.
- **hr** (string): Horário de referência da geração das informações
- **l** (dict): Relação de linhas localizadas onde:
    - **c** (string):   Letreiro completo
    - **cl** (int):  Código identificador da linha
    - **sl** (int):  Sentido de operação onde 1 significa de Terminal Principal para Terminal Secundário e 2 de Terminal Secundário para Terminal Principal
    - **lt0** (string): Letreiro de destino da linha
    - **lt1** (string): Letreiro de origem da linha
    - **qv** (int):  Quantidade de veículos localizados
    - **vs** (dict): Relação de veículos localizados, onde:
        - **p** (int):  Prefixo do veículo
        - **a** (bool):  Indica se o veículo é (true) ou não (false) acessível para pessoas com deficiência
        - **ta** (string): Indica o horário universal (UTC) em que a localização foi capturada. Essa informação está no padrão ISO 8601
        - **py** (double): Informação de latitude da localização do veículo
        - **px** (double): Informação de longitude da localização do veículo

In [12]:
# Funções auxiliares
import pandas as pd

def extrair_dados_empresas(resposta_api):
    """
    Extrai os dados das empresas da resposta da API.

    Parâmetros:
        resposta_api (dict): A resposta da API.

    Retorna:
        list: Uma lista de dicionários, cada um representando uma empresa.
    """
    dados_empresas = []  # Lista para armazenar os dados das empresas
    
    # Iterando sobre a resposta para extrair os dados
    for area in resposta_api["e"]:
        for empresa in area["e"]:
            # Cria um dicionário com os dados de cada empresa e adiciona à lista
            dados_empresas.append({"c": empresa["c"], "n": empresa["n"]})
    
    return dados_empresas

def criar_dataframe_empresas(dados_empresas):
    """
    Cria um DataFrame a partir de uma lista de dicionários com dados das empresas.

    Parâmetros:
        dados_empresas (list): Lista de dicionários com dados das empresas.

    Retorna:
        DataFrame: Um DataFrame contendo os dados das empresas.
    """
    return pd.DataFrame(dados_empresas)

# Faz uma chamada para buscar informações sobre as empresas operadoras de transporte
empresas = api.buscar_empresas()

dados_empresas = extrair_dados_empresas(empresas)
# print(dados_empresas)
df_dados_empresas = criar_dataframe_empresas(dados_empresas)

# Exibir o novo DataFrame contendo as informações de 'c' e 'n'
print(df_dados_empresas.head())

# Recupera Posição da Linha na garagem
nome_empresa = dados_empresas[4]['n']
codigo_empresa = dados_empresas[4]['c']

# Recupera código de uma linha (178L-10)
linha = '178L'
codigo_linha = api.buscar_linha(linha)[1]['cl']    # 0 significa que é a linha de ida e 1 a linha de volta

print(f"\nCódigo da empresa {nome_empresa}: {codigo_empresa}\n")
print(f"Código da Linha {linha}: {codigo_linha}\n")

# Chamada para recuperar a posição dos veículos de uma empresa na garagem (opcionalmente pode ter a linha também)
posicao = api.posicao_garagem(codigo_empresa, codigo_linha)
# print(posicao)

df_posicao = pd.DataFrame(posicao)
df_posicao

     c                n
0   37       GATO PRETO
1   38    SANTA BRIGIDA
2  232          Spencer
3  235  Norte Buss S.A.
4   92         SAMBAIBA

Código da empresa SAMBAIBA: 92

Código da Linha 178L: 33328

      hr                                                  l
0  08:56  {'c': '178L-10', 'cl': 33328, 'sl': 2, 'lt0': ...

---

### Previsão de Chegada

Retorna uma lista com a previsão de chegada dos veículos da linha informada que atende ao ponto de parada informado.

#### Argumento
- **codigoParada** (int): Código identificador da parada. Este é um código identificador único de cada ponto de parada do sistema (por sentido) e pode ser obtido através do método buscar_paradas
- **codigoLinha** (int): Código identificador da linha. Este é um código identificador único de cada linha do sistema (por sentido) e pode ser obtido através do método buscar_linha

#### Retorno
A resposta da API convertida em um dicionário Python, ou None se a requisição falhar.
- **hr** (string): Horário de referência da geração das informações
- **p** (dict):  Representa um ponto de parada onde:
    - **cp** (int):  Código identificador da parada
    - **np** (string):  Nome da parada
    - **py** (double): Informação de latitude da localização do veículo
    - **px** (double): Informação de longitude da localização do veículo
    - **l** (dict): Relação de veículos localizados, onde:
        - **c** (string):  Letreiro completo
        - **cl** (int):  Código identificador da linha
        - **sl** (int):  Sentido de operação onde 1 significa de Terminal Principal para Terminal Secundário e 2 de Terminal Secundário para Terminal Principal
        - **lt0** (string): Letreiro de destino da linha
        - **lt1** (string): Letreiro de origem da linha
        - **qv** (int):  Quantidade de veículos localizados
        - **vs** (dict):  Relação de veículos localizados, onde:
            - **p** (int):  Prefixo do veículo
            - **t** (string):  Horário previsto para chegada do veículo no ponto de parada relacionado
            - **a** (bool):  Indica se o veículo é (true) ou não (false) acessível para pessoas com deficiência
            - **ta** (string): Indica o horário universal (UTC) em que a localização foi capturada. Essa informação está no padrão ISO 8601
            - **py** (double): Informação de latitude da localização do veículo
            - **px** (double): Informação de longitude da localização do veículo

In [13]:
# Faz uma chamada para buscar informações sobre parada específica
codigo_parada = api.buscar_parada('Duilio')
# print(codigo_parada)
codigo_parada = codigo_parada[0]['cp']

# Faz uma chamada para buscar informações sobre o sentido da linha 8622
codigo_linha_sentido = api.buscar_linha_sentido('8622','2')
# print(codigo_linha_sentido)
codigo_linha_sentido = codigo_linha_sentido[0]['cl']

# Faz chamada para buscar Previsão de Chegada
previsao = api.previsao_chegada(codigo_parada, codigo_linha_sentido)
# print(codigo_parada)
# print(codigo_linha_sentido)
print(previsao)

# Imprime  informações sobre previsão de chegada da linha 8622 na parada Duílio
import pandas as pd
df_previsao = pd.DataFrame(previsao)
df_previsao

{'hr': '08:56', 'p': {'cp': 480014609, 'np': 'DUILIO C/B', 'py': -23.522627, 'px': -46.692121, 'l': [{'c': '8622-10', 'cl': 33206, 'sl': 2, 'lt0': 'PÇA. RAMOS DE AZEVEDO', 'lt1': 'MORRO DOCE', 'qv': 2, 'vs': [{'p': '11985', 't': '08:57', 'a': True, 'ta': '2024-05-19T11:56:24Z', 'py': -23.523915000000002, 'px': -46.68466166666667, 'sv': None, 'is': None}, {'p': '11964', 't': '09:09', 'a': True, 'ta': '2024-05-19T11:56:19Z', 'py': -23.537148333333334, 'px': -46.64946166666667, 'sv': None, 'is': None}]}]}}

       hr                                                  p
cp  08:56                                          480014609
np  08:56                                         DUILIO C/B
py  08:56                                         -23.522627
px  08:56                                         -46.692121
l   08:56  [{'c': '8622-10', 'cl': 33206, 'sl': 2, 'lt0':...

---

### Previsão de Chegada da Linha em todas as suas paradas
Retorna uma lista com a previsão de chegada de cada um dos veículos da linha informada em todos os pontos de parada aos quais que ela atende.

#### Argumento
- **codigoLinha** (int): Código identificador da linha. Este é um código identificador único de cada linha do sistema (por sentido) e pode ser obtido através do método buscar_linha

#### Retorno
A resposta da API convertida em um dicionário Python, ou None se a requisição falhar.
- **hr** (string): Horário de referência da geração das informações
- **ps** (dict): Representa uma relação de pontos de parada onde:
    - **cp** (int): Código identificador da parada
    - **np** (string): Nome da parada
    - **py** (double): Informação de latitude da localização do veículo
    - **px** (double): Informação de longitude da localização do veículo
    - **vs** (dict): Relação de veículos localizados, onde:
        - **p** (int):  Prefixo do veículo
        - **t** (string):  Horário previsto para chegada do veículo no ponto de parada relacionado
        - **a** (bool):  Indica se o veículo é (true) ou não (false) acessível para pessoas com deficiência
        - **ta** (string): Indica o horário universal (UTC) em que a localização foi capturada. Essa informação está no padrão ISO 8601
        - **py** (double): Informação de latitude da localização do veículo
        - **px** (double): Informação de longitude da localização do veículo

In [14]:
# Faz uma chamada para buscar informações sobre o sentido da linha 8622
codigo_linha_sentido = api.buscar_linha_sentido('8622','2')
# print(codigo_linha_sentido)
codigo_linha_sentido = codigo_linha_sentido[0]['cl']


# Faz chamada para buscar Previsão de Chegada da Linha em suas paradas
previsao_linha = api.previsao_chegada_linha(codigo_linha_sentido)
print(codigo_linha_sentido)
print(previsao_linha)

# Imprime  informações sobre previsão de chegada da linha 8622 na parada Duílio
import pandas as pd
df_previsao_linha = pd.DataFrame(previsao_linha)
df_previsao_linha

33206
{'hr': '08:56', 'ps': [{'cp': 700016624, 'np': 'ANA CINTRA C/B', 'py': -23.538357, 'px': -46.64733, 'vs': []}, {'cp': 7014416, 'np': 'ANGELICA C/B', 'py': -23.534377, 'px': -46.654322, 'vs': [{'p': '11964', 't': '08:58', 'a': True, 'ta': '2024-05-19T11:56:19Z', 'py': -23.537148333333334, 'px': -46.64946166666667, 'sv': None, 'is': None}]}, {'cp': 60016785, 'np': 'ANTARTICA C/B', 'py': -23.52622, 'px': -46.674187, 'vs': [{'p': '11964', 't': '09:04', 'a': True, 'ta': '2024-05-19T11:56:19Z', 'py': -23.537148333333334, 'px': -46.64946166666667, 'sv': None, 'is': None}]}, {'cp': 614432, 'np': 'BABY BARIONY C/B', 'py': -23.527608, 'px': -46.671511, 'vs': [{'p': '11964', 't': '09:03', 'a': True, 'ta': '2024-05-19T11:56:19Z', 'py': -23.537148333333334, 'px': -46.64946166666667, 'sv': None, 'is': None}]}, {'cp': 480014609, 'np': 'DUILIO C/B', 'py': -23.522627, 'px': -46.692121, 'vs': [{'p': '11985', 't': '08:57', 'a': True, 'ta': '2024-05-19T11:56:24Z', 'py': -23.523915000000002, 'px': -46.68466166666667, 'sv': None, 'is': None}, {'p': '11964', 't': '09:09', 'a': True, 'ta': '2024-05-19T11:56:19Z', 'py': -23.537148333333334, 'px': -46.64946166666667, 'sv': None, 'is': None}]}, {'cp': 700016865, 'np': 'NOTHMANN C/B', 'py': -23.536498, 'px': -46.650579, 'vs': []}, {'cp': 700016792, 'np': 'PACAEMBU C/B', 'py': -23.531864, 'px': -46.660859, 'vs': [{'p': '11964', 't': '09:00', 'a': True, 'ta': '2024-05-19T11:56:19Z', 'py': -23.537148333333334, 'px': -46.64946166666667, 'sv': None, 'is': None}]}, {'cp': 60016783, 'np': 'PARADA PALMEIRAS C/B', 'py': -23.525653, 'px': -46.679493, 'vs': [{'p': '11964', 't': '09:05', 'a': True, 'ta': '2024-05-19T11:56:19Z', 'py': -23.537148333333334, 'px': -46.64946166666667, 'sv': None, 'is': None}]}, {'cp': 60016789, 'np': 'PQ. DA ÁGUA BRANCA C/B', 'py': -23.529636, 'px': -46.667777, 'vs': [{'p': '11964', 't': '09:02', 'a': True, 'ta': '2024-05-19T11:56:19Z', 'py': -23.537148333333334, 'px': -46.64946166666667, 'sv': None, 'is': None}]}, {'cp': 700006085, 'np': 'ROSA E SILVA C/B', 'py': -23.532629, 'px': -46.657465, 'vs': [{'p': '11964', 't': '08:59', 'a': True, 'ta': '2024-05-19T11:56:19Z', 'py': -23.537148333333334, 'px': -46.64946166666667, 'sv': None, 'is': None}]}, {'cp': 60014604, 'np': 'SESC POMPEIA C/B', 'py': -23.525262, 'px': -46.682254, 'vs': [{'p': '11964', 't': '09:07', 'a': True, 'ta': '2024-05-19T11:56:19Z', 'py': -23.537148333333334, 'px': -46.64946166666667, 'sv': None, 'is': None}]}, {'cp': 480014610, 'np': 'TENDAL DA LAPA C/B', 'py': -23.522339, 'px': -46.696246, 'vs': [{'p': '11985', 't': '08:58', 'a': True, 'ta': '2024-05-19T11:56:24Z', 'py': -23.523915000000002, 'px': -46.68466166666667, 'sv': None, 'is': None}, {'p': '11964', 't': '09:10', 'a': True, 'ta': '2024-05-19T11:56:19Z', 'py': -23.537148333333334, 'px': -46.64946166666667, 'sv': None, 'is': None}]}, {'cp': 480014608, 'np': 'TIBERIO C/B', 'py': -23.522875, 'px': -46.688219, 'vs': [{'p': '11964', 't': '09:08', 'a': True, 'ta': '2024-05-19T11:56:19Z', 'py': -23.537148333333334, 'px': -46.64946166666667, 'sv': None, 'is': None}]}]}

       hr                                                 ps
0   08:56  {'cp': 700016624, 'np': 'ANA CINTRA C/B', 'py'...
1   08:56  {'cp': 7014416, 'np': 'ANGELICA C/B', 'py': -2...
2   08:56  {'cp': 60016785, 'np': 'ANTARTICA C/B', 'py': ...
3   08:56  {'cp': 614432, 'np': 'BABY BARIONY C/B', 'py':...
4   08:56  {'cp': 480014609, 'np': 'DUILIO C/B', 'py': -2...
5   08:56  {'cp': 700016865, 'np': 'NOTHMANN C/B', 'py': ...
6   08:56  {'cp': 700016792, 'np': 'PACAEMBU C/B', 'py': ...
7   08:56  {'cp': 60016783, 'np': 'PARADA PALMEIRAS C/B',...
8   08:56  {'cp': 60016789, 'np': 'PQ. DA ÁGUA BRANCA C/B...
9   08:56  {'cp': 700006085, 'np': 'ROSA E SILVA C/B', 'p...
10  08:56  {'cp': 60014604, 'np': 'SESC POMPEIA C/B', 'py...
11  08:56  {'cp': 480014610, 'np': 'TENDAL DA LAPA C/B', ...
12  08:56  {'cp': 480014608, 'np': 'TIBERIO C/B', 'py': -...

---

### Previsão de Chegada de Cada Linha na Parada

Retorna uma lista com a previsão de chegada dos veículos de cada uma das linhas que atendem ao ponto de parada informado.

#### Argumento
- **codigoParada** (int): Código identificador da parada. Este é um código identificador único de cada ponto de parada do sistema (por sentido) e pode ser obtido através do método buscar_paradas

#### Retorno
A resposta da API convertida em um dicionário Python, ou None se a requisição falhar.
- **hr** (string): Horário de referência da geração das informações
- **p** (dict): Representa um ponto de parada onde:
    - **cp** (int): Código identificador da parada
    - **np** (string): Nome da parada
    - **py** (double): Informação de latitude da localização do veículo
    - **px** (double): Informação de longitude da localização do veículo
    - **l** (dict): Relação de linhas localizadas onde:
        - **c** (string):  Letreiro completo
        - **cl** (int):  Código identificador da linha
        - **sl** (int):  Sentido de operação onde 1 significa de Terminal Principal para Terminal Secundário e 2 de Terminal Secundário para Terminal Principal
        - **lt0** (string): Letreiro de destino da linha
        - **lt1** (string): Letreiro de origem da linha
        - **qv** (int):  Quantidade de veículos localizados
        - **vs** (dict): Relação de veículos localizados, onde:
            - **p** (int):  Prefixo do veículo
            - **t** (string):  Horário previsto para chegada do veículo no ponto de parada relacionado
            - **a** (bool):  Indica se o veículo é (true) ou não (false) acessível para pessoas com deficiência
            - **ta** (string): Indica o horário universal (UTC) em que a localização foi capturada. Essa informação está no padrão ISO 8601
            - **py** (double): Informação de latitude da localização do veículo
            - **px** (double): Informação de longitude da localização do veículo

In [15]:
# Faz uma chamada para buscar informações sobre parada específica
codigo_parada = api.buscar_parada('Duilio')
# print(codigo_parada)
codigo_parada = codigo_parada[0]['cp']

# Faz chamada para buscar Previsão de Chegada da Linha em parada específica
previsao = api.previsao_parada(codigo_parada)
print(previsao)

# Imprime  informações sobre previsão de chegada da linha 8622 na parada Duílio
import pandas as pd
df_previsao = pd.DataFrame(previsao)
df_previsao

{'hr': '08:56', 'p': {'cp': 480014609, 'np': 'DUILIO C/B', 'py': -23.522627, 'px': -46.692121, 'l': [{'c': '8622-10', 'cl': 33206, 'sl': 2, 'lt0': 'PÇA. RAMOS DE AZEVEDO', 'lt1': 'MORRO DOCE', 'qv': 2, 'vs': [{'p': '11985', 't': '08:57', 'a': True, 'ta': '2024-05-19T11:56:24Z', 'py': -23.523915000000002, 'px': -46.68466166666667, 'sv': None, 'is': None}, {'p': '11964', 't': '09:09', 'a': True, 'ta': '2024-05-19T11:56:19Z', 'py': -23.537148333333334, 'px': -46.64946166666667, 'sv': None, 'is': None}]}, {'c': '8000-1', 'cl': 35274, 'sl': 2, 'lt0': 'PÇA. RAMOS DE AZEVEDO', 'lt1': 'TERM. LAPA', 'qv': 2, 'vs': [{'p': '12554', 't': '08:57', 'a': True, 'ta': '2024-05-19T11:56:18Z', 'py': -23.523978333333336, 'px': -46.684675, 'sv': None, 'is': None}, {'p': '12645', 't': '09:08', 'a': True, 'ta': '2024-05-19T11:56:29Z', 'py': -23.536433333333335, 'px': -46.650724999999994, 'sv': None, 'is': None}]}, {'c': '178A-10', 'cl': 558, 'sl': 1, 'lt0': 'LAPA', 'lt1': 'METRÔ SANTANA', 'qv': 1, 'vs': [{'p': '21355', 't': '08:58', 'a': True, 'ta': '2024-05-19T11:56:26Z', 'py': -23.525125000000003, 'px': -46.682415000000006, 'sv': None, 'is': None}]}, {'c': '8545-10', 'cl': 34132, 'sl': 2, 'lt0': 'METRÔ BARRA FUNDA', 'lt1': 'PENTEADO', 'qv': 1, 'vs': [{'p': '13547', 't': '08:59', 'a': True, 'ta': '2024-05-19T11:56:03Z', 'py': -23.526625, 'px': -46.68191333333333, 'sv': None, 'is': None}]}, {'c': '856R-10', 'cl': 34196, 'sl': 2, 'lt0': 'SOCORRO', 'lt1': 'LAPA', 'qv': 2, 'vs': [{'p': '82624', 't': '09:00', 'a': True, 'ta': '2024-05-19T11:56:08Z', 'py': -23.529088333333334, 'px': -46.67825166666667, 'sv': None, 'is': None}, {'p': '82573', 't': '09:26', 'a': True, 'ta': '2024-05-19T11:56:26Z', 'py': -23.58129, 'px': -46.68422166666666, 'sv': None, 'is': None}]}, {'c': '8677-10', 'cl': 33211, 'sl': 2, 'lt0': 'LGO. DO PAISSANDÚ', 'lt1': 'JD. LÍBANO', 'qv': 1, 'vs': [{'p': '11801', 't': '09:06', 'a': True, 'ta': '2024-05-19T11:55:57Z', 'py': -23.532741666666666, 'px': -46.65659666666667, 'sv': None, 'is': None}]}, {'c': '978J-10', 'cl': 33359, 'sl': 2, 'lt0': 'TERM. PRINC. ISABEL', 'lt1': 'VOITH', 'qv': 1, 'vs': [{'p': '11757', 't': '09:06', 'a': True, 'ta': '2024-05-19T11:56:15Z', 'py': -23.533236666666667, 'px': -46.656415, 'sv': None, 'is': None}]}, {'c': '8615-10', 'cl': 34107, 'sl': 2, 'lt0': 'TERM. PQ. D. PEDRO II', 'lt1': 'PQ. DA LAPA', 'qv': 1, 'vs': [{'p': '82663', 't': '09:11', 'a': True, 'ta': '2024-05-19T11:56:20Z', 'py': -23.539858333333335, 'px': -46.64459166666667, 'sv': None, 'is': None}]}, {'c': '8594-10', 'cl': 33200, 'sl': 2, 'lt0': 'PÇA. RAMOS DE AZEVEDO', 'lt1': "CID. D'ABRIL ", 'qv': 1, 'vs': [{'p': '11831', 't': '09:11', 'a': True, 'ta': '2024-05-19T11:56:05Z', 'py': -23.540399999999998, 'px': -46.64376333333333, 'sv': None, 'is': None}]}, {'c': '874T-10', 'cl': 307, 'sl': 1, 'lt0': 'LAPA', 'lt1': 'IPIRANGA', 'qv': 1, 'vs': [{'p': '52135', 't': '09:55', 'a': True, 'ta': '2024-05-19T11:56:10Z', 'py': -23.577173333333334, 'px': -46.60862166666667, 'sv': None, 'is': None}]}]}}

       hr                                                  p
cp  08:56                                          480014609
np  08:56                                         DUILIO C/B
py  08:56                                         -23.522627
px  08:56                                         -46.692121
l   08:56  [{'c': '8622-10', 'cl': 33206, 'sl': 2, 'lt0':...

---

### Velocidades Médias na cidade

Retorna o mapa completo da cidade contendo um mapa de fluidez da cidade com a velocidade média e tempo de percurso de cada trecho envolvido.

#### Argumentos
sentido (string): Se desejar a informação separada de um único sentido será preciso indicar aqui.
Os valores possíveis são:
 - BC - veículos saindo do bairro em direção ao centro
 - CB - veículos saindo do centro em direção ao bairro

#### Retorno
 - str: O caminho para o arquivo KMZ baixado, ou None se a requisição falhar.

In [16]:
# Chamada para API Olho Vivo para buscar informações de Velocidade Média da Cidade
kmz_pathway = api.velocidade_media_cidade("BC")

##### Extração dos dados do mkz retornado

In [17]:
import re
from zipfile import ZipFile
from bs4 import BeautifulSoup
import html

def extract_kml_from_kmz(kmz_pathway):
    """
    Extrai o arquivo KML de um arquivo KMZ.

    Args:
        kmz_pathway: O caminho para o arquivo KMZ.

    Returns:
        O conteúdo do arquivo KML como uma string.
    """
    try:
        with ZipFile(kmz_pathway, 'r') as kmz:
            # List all files in the KMZ archive
            unzip_file_list = kmz.namelist()
            # Get the KML file
            kml_file_name = 'TBC.kml' if 'TBC.kml' in unzip_file_list else unzip_file_list[0]
            # Open and read the KML file
            with kmz.open(kml_file_name, 'r') as kml_file:
                kml_content = kml_file.read().decode('utf-8')
            
            return kml_content
    except Exception as e:
        raise e

def parse_description(description):
    """
    Analisa a string de descrição em um dicionário estruturado, substituindo valores vazios, "0" e "--" por "-1".
    Garante que todas as chaves estejam presentes no dicionário final.

    Argumentos:
        description: A string de descrição de um Placemark.

    Retorna:
        Um dicionário com a descrição estruturada.
    """
    description_dict = {}
    parts = description.split(';')

    # Função para tratar valores especiais
    def tratar_valor(value):
        if value in {"", "0", "--"}:
            return -1
        return value

    # Map description parts to dictionary keys
    for i in range(0, len(parts) - 1, 2):
        key = parts[i].strip().rstrip(':')
        value = parts[i + 1].strip()
        value = tratar_valor(value)

        if key == 'Trecho':
            description_dict['trecho'] = value
        elif key == 'Referência':
            description_dict['referencia'] = value
        elif key == 'Extensão (metros)':
            try:
                description_dict['extensao_metros'] = int(value.replace('.', '')) if isinstance(value, str) else value
            except ValueError:
                description_dict['extensao_metros'] = tratar_valor(value)  # Preserve original value if not a number
        elif key == 'Velocidade média do trecho':
            try:
                description_dict['velocidade_media_trecho_kmh'] = int(value.split()[0]) if isinstance(value, str) else value
            except ValueError:
                description_dict['velocidade_media_trecho_kmh'] = tratar_valor(value)  # Preserve original value if not a number
        elif key == 'Tempo médio do percurso':
            try:
                if isinstance(value, str):
                    hours, minutes = map(int, value.split('h'))
                    total_minutes = hours * 60 + minutes
                    description_dict['tempo_medio_percurso_minutos'] = total_minutes
                else:
                    description_dict['tempo_medio_percurso_minutos'] = value
            except ValueError:
                description_dict['tempo_medio_percurso_minutos'] = tratar_valor(value)  # Preserve original value if not a valid time format
        elif key == 'Velocidade média do corredor':
            try:
                description_dict['velocidade_media_corredor_kmh'] = int(value.split()[0]) if isinstance(value, str) else value
            except ValueError:
                description_dict['velocidade_media_corredor_kmh'] = tratar_valor(value)  # Preserve original value if not a number

    # Garantir que todas as chaves estejam presentes
    required_keys = ['trecho', 'referencia', 'extensao_metros', 'velocidade_media_trecho_kmh', 'tempo_medio_percurso_minutos', 'velocidade_media_corredor_kmh']
    for key in required_keys:
        if key not in description_dict:
            description_dict[key] = -1

    return description_dict


def read_kml_content(kml_content):
    """
    Extrai dados de texto das descrições e coordenadas de todos os Placemarks de um arquivo KML, preservando o texto e removendo tags e entidades HTML.
    Usa o ponto e vírgula como separador entre diferentes descrições.

    Args:
        kml_content: O conteúdo do arquivo KML como uma string.

    Returns:
        Uma lista de dicionários com descrições e coordenadas para cada Placemark.
    """
    placemarks = []
    for placemark in kml_content.split('<Placemark'):
        if not placemark.strip():
            continue
        
        placemark_data = {}
        
        # Extract description
        description_start = placemark.find('<description>')
        description_end = placemark.find('</description>')
        if description_start != -1 and description_end != -1:
            description = placemark[description_start + len('<description>'): description_end]
            description = html.unescape(description)
            soup = BeautifulSoup(description, 'html.parser')
            text_only_description = soup.get_text(separator=';', strip=True)
            structured_description = parse_description(text_only_description)
            placemark_data.update(structured_description)  # Merge description keys into placemark_data

        # Extract coordinates
        coordinates_start = placemark.find('<coordinates>')
        coordinates_end = placemark.find('</coordinates>')
        if coordinates_start != -1 and coordinates_end != -1:
            coordinates = placemark[coordinates_start + len('<coordinates>'): coordinates_end]
            coordinates = coordinates.strip().split()
            coordinates = [coord.split(',')[:2] for coord in coordinates]  # Discarding the third value
            placemark_data['coordenadas'] = coordinates
        else:
            placemark_data['coordenadas'] = -1

        placemarks.append(placemark_data)
    
    return placemarks

In [18]:
kmz_pathway = api.velocidade_media_cidade("BC")

# Extrai o conteúdo do arquivo KML do arquivo KMZ
kml_content = extract_kml_from_kmz(kmz_pathway)

# Lê o conteúdo do arquivo KML e extrai as descrições e coordenadas
trechos = read_kml_content(kml_content)

In [19]:
# print(trechos)
import pandas as pd
df_trechos = pd.DataFrame(trechos)
df_trechos

,trecho,referencia,extensao_metros,velocidade_media_trecho_kmh,tempo_medio_percurso_minutos,velocidade_media_corredor_kmh,coordenadas
0,-1,-1,-1,-1,-1,-1,-1
1,de T PARELHEIROS até T VARGINHA,AV. SADAMU INOUE,7549,26,17,26,"[[-46.717208, -23.767495], [-46.717241, -23.76..."
2,de T VARGINHA até AV. DA. BELMIRA MARIN,AV. SENADOR TEOTONIO VILELA,3467,27,7,26,"[[-46.717208, -23.767495], [-46.717035, -23.76..."
3,de AV. DA. BELMIRA MARIN até E T RIO BONITO,AV. SENADOR TEOTONIO VILELA,2319,26,5,26,"[[-46.698738, -23.718592], [-46.69879, -23.718..."
4,de E T RIO BONITO até PONTE DO SOCORRO,AV. ROBERT KENNEDY,5640,29,11,26,"[[-46.698738, -23.718592], [-46.69879, -23.718..."
...,...,...,...,...,...,...,...
318,de AV. HELIO PELLEGRINO até AV. NOVE DE JULHO,AV. STO. AMARO - AV. S. GABRIEL,1834,23,4,26,"[[-46.671133, -23.576909], [-46.671121, -23.57..."
319,de AV. SÃO GABRIEL até TERM. BANDEIRA,AV NOVE DE JULHO,4445,28,9,26,"[[-46.640368, -23.549191], [-46.640462, -23.54..."
320,de TERM. SACOMÃ até TERM. MERCADO,EXPRESSO TIRADENTES,7568,46,9,46,"[[-46.602889, -23.602958], [-46.602262, -23.60..."
321,de AV. D. PEDRO I até LGO. CAMBUCI,R. CLÍMACO BARBOSA,1404,26,3,-1,"[[-46.621526, -23.562285], [-46.620594, -23.56..."
322,de LGO. CAMBUCI até AV. LIBERDADE,R. LUÍS GAMA/ R. SILVEIRA MOTA,2166,19,6,-1,"[[-46.636945, -23.558267], [-46.635791, -23.55..."

In [20]:
df_trechos.to_excel('trechos.xlsx', index=False)