# Utilizando módulo Olho Vivo API

Módulos necessários até o momento:
- python-dotenv
- requests
- pandas

Para instalar no ambiente:
```
pip install python-dotenv requests pandas
```

---

In [43]:
# Importa dependências

import os
from dotenv import load_dotenv

Aqui é importante que seja copiado manualmente o arquivo .env com o TOKEN de acesso para a API do Olho Vivo.

Ref: https://www.sptrans.com.br/desenvolvedores/api-do-olho-vivo-guia-de-referencia/

In [44]:
# Importa o módulo api_olhovivo e autentica no Olho Vivo API
import sys
sys.path.insert(0, '../modules')
import api_olhovivo

load_dotenv()  # Carrega as variáveis de ambiente do arquivo .env
# Acesse o token de API do arquivo .env
api_token = os.getenv("API_TOKEN")

api = api_olhovivo.OlhoVivoAPI(api_token)

Autenticação bem-sucedida!

---

### Buscar informação de Linha de Ônibus
#### Argumento
- **termosBusca** (str): Aceita denominação ou número da linha (total ou parcial).
Exemplo: 8000, Lapa ou Ramos

#### Retorno
A resposta da API convertida em um dicionário Python, ou None se a requisição falhar.
- **cl** (int): Código identificador da linha. Este é um código identificador único de cada linha do sistema (por sentido de operação)
- **lc** (bool): Indica se uma linha opera no modo circular (sem um terminal secundário)
- **lt** (string): Informa a primeira parte do letreiro numérico da linha
- **tl** (int): Informa a segunda parte do letreiro numérico da linha, que indica se a linha opera nos modos: BASE (10), ATENDIMENTO (21, 23, 32, 41)
- **sl** (int): Informa o sentido ao qual a linha atende, onde 1 significa Terminal Principal para Terminal Secundário e 2 para Terminal Secundário para Terminal Principal
- **tp** (string): Informa o letreiro descritivo da linha no sentido Terminal Principal para Terminal Secundário
- **ts** (string): Informa o letreiro descritivo da linha no sentido Terminal Secundário para Terminal Principal

In [45]:
# Faz uma chamada para obter informações sobre a linha 8040
info_linha = api.buscar_linha('8040')


# Imprime  informações sobre a linha 8040
import pandas as pd
df_info_linhas = pd.DataFrame(info_linha)
df_info_linhas

      cl     lc    lt  sl  tl          tp            ts
0    406  False  8040   1  10  TERM. LAPA  SOL NASCENTE
1  33174  False  8040   2  10  TERM. LAPA  SOL NASCENTE

---

### Buscar informação de Linha de Ônibus em sentido específico
Realiza uma busca das linhas do sistema com base no sentido da linha. Se a linha não é encontrada então é realizada uma busca fonetizada na denominação das linhas.

#### Argumento
- **codigoLinha** (str): O código da linha.
- **sentido** (str): O sentido da linha (1- ida ou 2-volta).

#### Retorno
A resposta da API convertida em um dicionário Python, ou None se a requisição falhar.
- **cl** (int): Código identificador da linha. Este é um código identificador único de cada linha do sistema (por sentido de operação)
- **lc** (bool): Indica se uma linha opera no modo circular (sem um terminal secundário)
- **lt** (string): Informa a primeira parte do letreiro numérico da linha
- **tl** (int): Informa a segunda parte do letreiro numérico da linha, que indica se a linha opera nos modos: BASE (10), ATENDIMENTO (21, 23, 32, 41)
- **sl** (int): Informa o sentido ao qual a linha atende, onde 1 significa Terminal Principal para Terminal Secundário e 2 para Terminal Secundário para Terminal Principal
- **tp** (string): Informa o letreiro descritivo da linha no sentido Terminal Principal para Terminal Secundário
- **ts** (string): Informa o letreiro descritivo da linha no sentido Terminal Secundário para Terminal Principal

In [46]:
# Faz uma chamada para buscar informações sobre o sentido da linha 8040
info_linha_sentido = api.buscar_linha_sentido('8040','1')


# Imprime  informações sobre a linha 8040
import pandas as pd
df_info_linha_sentido = pd.DataFrame(info_linha_sentido)
df_info_linha_sentido

    cl     lc    lt  sl  tl          tp            ts
0  406  False  8040   1  10  TERM. LAPA  SOL NASCENTE

---

### Buscar paradas
Realiza uma busca fonética das paradas de ônibus do sistema com base no parâmetro informado. A consulta é realizada no nome da parada e também no seu endereço de localização.
        
#### Argumentos:
- **termosBusca** (str): Aceita nome da parada ou endereço de localização (total ou parcial).
Exemplo: Afonso, ou Balthazar da Veiga

#### Retorno:
A resposta da API convertida em um dicionário Python, ou None se a requisição falhar.
- **cp** (int): Código identificador da parada
- **np** (string): Nome da parada
- **ed** (string): Endereço de localização da parada
- **py** (double): Latitude da parada
- **px** (double): Longitude da parada

In [47]:
# Faz uma chamada para buscar informações sobre todas as paradas
info_paradas = api.buscar_paradas('Ciencia')


# Imprime  informações sobre a linha 8040
import pandas as pd
df_info_paradas = pd.DataFrame(info_paradas)
df_info_paradas

          cp           np                    ed         py         px
0  480014611  CIENCIA C/B  R SCIPIAO/ R AURELIA -23.521284 -46.698763

---

### Busca parada por Linha (Não está funcionando)
Realiza uma busca por todos os pontos de parada atendidos por uma determinada linha.

#### Argumento
- **codigoLinha** (str): Código identificador da linha. Este é um código identificador único de cada linha do sistema (por sentido) e pode ser obtido através do método buscar_linha da categoria Linhas

#### Retorno
A resposta da API convertida em um dicionário Python, ou None se a requisição falhar.
- **cp** (int): Código identificador da parada
- **np** (string): Nome da parada
- **ed** (string): Endereço de localização da parada
- **py** (double): Latitude da parada
- **px** (double): Longitude da parada

In [54]:
# Faz uma chamada para buscar informações sobre as paradas da linha 8040
info_linha = api.buscar_linha('8040')
codigo_linha = info_linha[1]['cl']

info_paradas_linha = api.buscar_paradas_por_linha('406')


print(codigo_linha)
print(info_paradas_linha)

33174
[]

---

### Buscar Corredores (Faltam dados)
Retorna uma lista com todos os corredores inteligentes.

Retorna:
A resposta da API convertida em um dicionário Python, ou None se a requisição falhar.
- **cc** (int): Código identificador da corredor. Este é um código identificador único de cada corredor inteligente do sistema
- **nc** (string): Nome do corredor

In [55]:
# Faz uma chamada para buscar informações sobre as paradas do corredor
corredores = api.buscar_corredores()


# Imprime  informações de corredores
import pandas as pd
df_corredores = pd.DataFrame(corredores)
df_corredores

   cc                   nc
0   8          Campo Limpo
1   9  Expresso Tiradentes
2   3      Inajar de Souza
3   7          Parelheiros
4   1             Pirituba
5   2          Santo Amaro
6  10       Paes de Barros

---

### Buscar Paradas em Corredor
Retorna a lista detalhada de todas as paradas que compõem um determinado corredor.

#### Argumento
- **codigoCorredor** (str): Código identificador do corredor. Este é um código identificador único de cada corredor do sistema e pode ser obtido através do método buscar_corredores.

#### Retorno
A resposta da API convertida em um dicionário Python, ou None se a requisição falhar.

In [56]:
# Faz uma chamada para buscar informações sobre as paradas do corredor 9
corredor = api.buscar_paradas_por_corredor('9')


# Imprime  informações de corredores
import pandas as pd
df_corredor = pd.DataFrame(corredor)
df_corredor

,cp,np,ed,py,px
0,3305795,CAY B/C,8000 - ESTACAO CAY BC,-23.574436,-46.603153
1,3305799,CAY C/B,8000 - ESTACAO CAY CB,-23.574453,-46.603180
2,1410076,ESTACAO ALBERTO LION B/C,6000 - ESTACAO ALBERTO LION BC,-23.564183,-46.611236
3,1410079,ESTACAO ALBERTO LION C/B,6000 - ESTACAO ALBERTO LION CB,-23.564195,-46.611271
4,1410078,ESTACAO ANA NERI C/B,5800 - ESTACAO ANA NERI CB,-23.559044,-46.614686
5,1410074,ESTAÇÃO METRÔ D. PEDRO B/C,5000 - ESTACAO METRO D. PEDRO BC,-23.550720,-46.626853
6,1410080,ESTAÇÃO METRÔ D. PEDRO C/B,5000 - ESTACAO METRO D. PEDRO CB,-23.550730,-46.626911
7,3305797,GRITO B/C,10000 - ESTACAO GRITO BC,-23.598138,-46.597172
8,3305801,GRITO C/B,10000 - ESTACAO GRITO CB,-23.598148,-46.597237
9,3305796,N.SRA APARECIDA B/C,9000 - ESTACAO NOSSA SENHORA DA APARECIDA (LEC...,-23.591353,-46.597779
10,3305800,N.SRA APARECIDA C/B,9000 - ESTACAO NOSSA SENHORA DA APARECIDA (LEC...,-23.591347,-46.597851